### ISSUE TITLE
Request for pushing this to the definitely types repo

### ISSUE THREAD

**Issue by RachelSatoyama** [typed-typings/npm-co#1]
Hi @blakeembrey ! Can you please create PR to the https://github.com/DefinitelyTyped/DefinitelyTyped - it's just that since new official way to install definitions is to just `npm install @types/<package-name>` instead of using `typings` this definition is not that easy both to find and to install.

**Comment by felixfbecker** [comment]
We do not have the capacity to contribute PRs to DT to keep all typings in the registry in sync with DT. Contributing to DT is cumbersome, you cannot subscribe issues/PRs on individual typings so they _will_ get out of sync eventually and we have 219 typings to maintain.

Please see https://github.com/Microsoft/types-publisher/issues/4
